
project:
  title: The proof assigment
  description: Have fun with coding
  version: 0.0.1
  rapydo: 0.6.3

variables:
  env:
    AUTH_SERVICE: mongo
    MONGO_DATABASE: proof
    FRONTEND_ENABLE: 0
    TOKEN_DEFAULT_TTL: 86400 # 1 day in seconds
    REACT_DEFAULT_PORT: 5000
